project:
  type: website
  render:
    - index.qmd
    - test_lab_warm_up.qmd
    
website:
  title: "Test Quarto RevealJS"
  navbar:
    search: true
    left:
      - text: "Home"
        file: index.qmd
      - text: "Lab warm-ups"
        file: test_lab_warm_up.qmd

format:
  html:
    theme: cosmo
    css: style.css
    toc: true